In [53]:
import pandas as pd
import os

In [54]:
data_path = "../data"
raw_dir = os.path.join(data_path, "raw")
processed_dir = os.path.join(data_path, "processed")

In [55]:
splits = ["train", "dev", "test"]

dfs = []
for split in splits:
	path = os.path.join(raw_dir, f"stsb-es-{split}.csv",)
	df = pd.read_csv(
		path,
		names=["sentence1", "sentence2", "score"]
	)
	df["split"] = split
	dfs.append(df)

In [56]:
df = pd.concat(dfs, ignore_index=True)
df["score_norm"] = df["score"] / 5

In [57]:
display(df)

,sentence1,sentence2,score,split,score_norm
0,Un avión está despegando.,Un avión está despegando.,5.00,train,1.00
1,Un hombre está tocando una gran flauta.,Un hombre está tocando una flauta.,3.80,train,0.76
2,Un hombre está untando queso rallado en una pi...,Un hombre está untando queso rallado en una pi...,3.80,train,0.76
3,Tres hombres están jugando al ajedrez.,Dos hombres están jugando al ajedrez.,2.60,train,0.52
4,Un hombre está tocando el violonchelo.,Un hombre sentado está tocando el violonchelo.,4.25,train,0.85
...,...,...,...,...,...
8623,Filipinas y el Canadá se comprometen a seguir ...,Filipinas salva 100 tras el hundimiento de un ...,0.00,test,0.00
8624,Israel impide a los palestinos entrar en la Ci...,La solución de dos estados entre los palestino...,1.00,test,0.20
8625,¿Cuánto sabes del Servicio Secreto?,Los legisladores de ambos lados expresan su in...,1.00,test,0.20
8626,Obama lucha por calmar los temores de los saud...,Myanmar lucha por finalizar las listas de vota...,0.00,test,0.00
8627,Corea del Sur declara el fin del brote de MERS,La delegación de Corea del Norte se reúne con ...,0.00,test,0.00

In [58]:
df.groupby("split")["score_norm"].describe()

        count      mean       std  min    25%   50%   75%  max
split
dev    1500.0  0.472782  0.300097  0.0  0.200  0.51  0.72  1.0
test   1379.0  0.521583  0.305103  0.0  0.263  0.56  0.76  1.0
train  5749.0  0.540200  0.292880  0.0  0.300  0.60  0.76  1.0

In [59]:
for split, data in df.groupby("split"):
	path = os.path.join(processed_dir, f"stsb-es-{split}.csv")
	data.to_csv(
		path,
		index=False
	)